config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :likes, only: [:create]

  devise_for :users

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @an_hour_ago = (Time.now.utc - 1*60*60).strftime("%d/%m/%Y %H:%M:%S %Z")

    @messages = Message.where(created_at: @an_hour_ago..)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: %i[ create destroy ]

  def create
    @message_id = params[:message_id]
    specified_message = Message.find_by(id: @message_id)
    if specified_message.nil?
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Couldn't like." }
        format.json { render :show, status: :unprocessable_entity }
      end
      return
    else
      an_hour_ago = (Time.now.utc - 1*60*60).strftime("%d/%m/%Y %H:%M:%S %Z")
      if specified_message.created_at < an_hour_ago
        respond_to do |format|
          format.html { redirect_to root_path, notice: "Couldn't like." }
          format.json { render :show, status: :unprocessable_entity }
        end
        return
      end
    end

    @user_id = current_user.id

    @previous_like = current_user.likes.find_by(user_id: @user_id, message_id: @message_id)
    if @previous_like.nil?
      @like = Like.new(user_id: @user_id, message_id: @message_id)

      respond_to do |format|
        if @like.save
          format.html { redirect_to root_path, notice: "Like was successfully created." }
          format.json { render :show, status: :created, location: @like }
        else
          format.html { redirect_to root_path, notice: "Couldn't like." }
          format.json { render :show, status: :unprocessable_entity }
        end
      end
    else
      @previous_like.destroy

      respond_to do |format|
        format.html { redirect_to root_path, notice: "Like was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ mine show edit update destroy ]
  before_action :authenticate_user!, except: %i[ show ]
  before_action :has_already_made_in_hour
  before_action :correct_user, only: %i[ edit update destroy ]

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages
  def index
    @messages = current_user.messages
  end

  def correct_user
    @owner = current_user.messages.find_by(id: params[:id])
    redirect_to messages_path, notice: "cacat" if @message.nil?
  end

  def has_already_made_in_hour
    an_hour_ago = (Time.now.utc - 1*60*60).strftime("%d/%m/%Y %H:%M:%S %Z")
    messages = Message.find_by(user_id: current_user.id, created_at: an_hour_ago..)
    @has_already_made_in_hour = !messages.nil?
  end

  # GET /messages/new
  def new
    @message = current_user.messages.build
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    #@message = Message.new(message_params)
    @message = current_user.messages.build(message_params)
    #@message.user_id = current_user.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:message)
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Hourly', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Previous", messages_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create", new_message_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Account", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p><%= @an_hour_ago %></p>

<div id="messages">
  <% @messages.each do |message| %>
    <p>
      <strong>Message: </strong>
      <%= message.message %>
      <strong> By: </strong>
      <%= message.user.email %>
      <strong> At: </strong>
      <%= message.created_at %>
      <strong> Id: </strong>
      <%= message.id %>
    </p>
    <p>
      <%= link_to "Show this message", message %> |
      <% unless current_user.nil? %>
        <%= button_to message.likes.any? { |like| like.user_id == current_user.id} ? "Unlike this message" : "Like this message", likes_path(:message_id => message.id), method: :post, remote: true %> |
        <% if message.user == current_user %>
          <%=  link_to "Edit this message", edit_message_path(message)  %>
        <% end %>
      <% end %>
    </p>
    <% message.likes.each do |like| %>
      <p><%= like.inspect %></p>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hourly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Message:</strong>
    <%= message.message %>
  </p>

</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.erb
<div id="messages">
  <% @messages.each do |message| %>
    <p>
      <strong>Message: </strong>
      <%= message.message %>
      <strong> At: </strong>
      <%= message.created_at %>
    </p>
    <p>
      <%= link_to "Show this message", message %> |
    </p>
  <% end %>
</div>

app/views/messages/new.html.erb
<h1>New message</h1>
<% if @has_already_made_in_hour %>
  <p>Already made this hour!</p>
<% else %>
  <%= render "form", message: @message  %>
<% end %>
<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>